import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#111111',
  '--slot4-page-text': '#ffffff',
  '--slot4-panel-bg': '#161616',
  '--slot4-surface-bg': '#161616',
  '--slot4-muted-text': '#8d8d8d',
  '--slot4-soft-muted-text': '#6b6b6b',
  '--slot4-accent': '#f07c30',
  '--slot4-accent-fill': '#f07c30',
  '--slot4-accent-soft': 'rgba(240,124,48,0.12)',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#0a0a0a',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#1f2020',
  '--slot4-cream': '#131313',
  '--slot4-warm': '#131313',
  '--slot4-lavender': '#161616',
  '--slot4-gray': '#161616',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#111111',
  '--editable-page-text': '#ffffff',
  '--editable-container': '1340px',
  '--editable-border': '#1f2020',
  '--editable-nav-bg': '#111111',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#f07c30',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#f07c30',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#161616',
  '--editable-footer-bg': '#0a0a0a',
  '--editable-footer-text': '#c7c7c7',
  '--editable-radius-control': '0.3125rem',
  '--editable-radius-card': '0.9375rem',
  '--editable-radius-pill': '99px',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_0_0_1px_rgba(255,255,255,0.04)]',
  shadowStrong: 'shadow-[0_4px_24px_rgba(0,0,0,0.5)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-medium uppercase tracking-[0.16em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-normal leading-[1.08] tracking-[-0.02em] sm:text-5xl lg:text-[3.625rem]',
    sectionTitle: 'text-3xl font-normal tracking-[-0.02em] sm:text-[2.875rem]',
    body: 'text-base leading-relaxed font-light',
  },
  surface: {
    card: `rounded-[var(--editable-radius-card)] border ${editablePalette.border} ${editablePalette.surfaceBg}`,
    soft: `rounded-[var(--editable-radius-card)] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[var(--editable-radius-card)] ${editablePalette.darkBg} ${editablePalette.darkText}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-[var(--editable-radius-control)] border border-[#38393a] bg-[#161616] px-6 py-3 text-sm font-medium text-white transition duration-300 hover:border-[var(--slot4-accent)] hover:scale-[0.96] active:scale-[0.94]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-[var(--editable-radius-control)] border border-[var(--editable-border)] bg-transparent px-6 py-3 text-sm font-medium text-[var(--slot4-muted-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-white hover:scale-[0.96]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-[var(--editable-radius-control)] bg-[var(--slot4-accent)] px-6 py-3 text-sm font-medium text-white transition duration-300 hover:brightness-110 hover:scale-[0.96] active:scale-[0.94]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[var(--editable-radius-card)] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-400 hover:-translate-y-1 hover:border-[var(--slot4-accent)]/40',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
